version: '3'

services:
  web:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src/
      - ./test:/app/test/
    ports: 
      - 3000:3333

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs